# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.IntegerField(null=True, verbose_name='\u5206\u7c7bID')),
                ('orderid', models.IntegerField(null=True, verbose_name='\u6392\u5e8fID')),
                ('name', models.CharField(default='', max_length=512, null=True, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('description', models.TextField(default='', null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
                ('addDate', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(default=0, null=True, verbose_name='\u6392\u5e8f')),
                ('favicon', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='\u56fe\u6807')),
                ('title', models.CharField(default='', max_length=128, null=True, verbose_name='\u6807\u9898')),
                ('atom', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='atom')),
                ('link', models.CharField(default='', max_length=128, null=True, verbose_name='\u94fe\u63a5')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='\u63cf\u8ff0')),
                ('lastBuildDate', models.DateTimeField(null=True, verbose_name='\u751f\u6210\u65e5\u671f')),
                ('language', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='\u8bed\u8a00')),
                ('addDate', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Category', verbose_name='\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u8ba2\u9605',
                'verbose_name_plural': '\u8ba2\u9605',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('reed', models.IntegerField(default=0, null=True, verbose_name='\u662f\u5426\u9605\u8bfb')),
                ('pic', models.CharField(default='', max_length=512, null=True, verbose_name='\u56fe\u7247')),
                ('title', models.CharField(default='', max_length=128, null=True, verbose_name='\u6807\u9898')),
                ('link', models.CharField(max_length=512, null=True, verbose_name='\u94fe\u63a5')),
                ('pubDate', models.DateTimeField(null=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('category', models.CharField(default='', max_length=128, null=True, verbose_name='\u6807\u7b7e')),
                ('description', models.TextField(default='', null=True, verbose_name='\u63cf\u8ff0')),
                ('content', models.TextField(default='', null=True, verbose_name='\u5185\u5bb9')),
                ('addDate', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('channelid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rss.Channel', verbose_name='\u8ba2\u9605\u6e90')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
